applicationIdSuffix=.wassce
versionCode=1
versionName=1.0.0
appSlug=wassce
appId=wassce
country=Nigeria
hasMultipleCountries=true
hasTheory=true
includeLiteraryTexts=true
hasNotes=true
appName=Scholarly WAEC CBT
school=
website=https://www.waecnigeria.org
dbName=waec_ssce.db
dbVersion=1
srcPath=src/waec/resources
stagingBaseURL=https://staging.wassce.scholarly.africa/api/v1/
prodBaseURL=https://wassce.scholarly.africa/api/v1/
stagingClientID=526557525284-gcou2jaatsdt1b6ai99akhjbc17qoosf.apps.googleusercontent.com
prodClientID=37358677765-bhju4ggpo5rhvg36dgsf0v490i3r4hov.apps.googleusercontent.com
paystackURL=https://paystack.com/pay/wassce-activation-pin-pc
welcomeTextOne=Access thousands of real WAEC Past Questions