applicationIdSuffix=.putme.oau
versionCodeWin=1
versionNameWin=1.0.0
appSlug=putme-oau
appId=oau_putme
country=Nigeria
hasMultipleCountries=false
hasTheory=false
includeLiteraryTexts=true
hasNotes=true
appName=Scholarly OAU Post Jamb CBT
school=oau
website=https://oauife.edu.ng
dbName=putme_oau.db
dbVersion=1
srcPath=src/putmeOau/resources
stagingBaseURL=https://staging.putme.scholarly.africa/api/v1/
prodBaseURL=https://putme.scholarly.africa/api/v1/
stagingClientID=924499222398-ne5djajgfceotaqcaj8pi1jabqbd5idn.apps.googleusercontent.com
prodClientID=616523094012-nend4jo42jod90sdha8sfsibmoa7b9t9.apps.googleusercontent.com
paystackURL=https://paystack.com/pay/postutme-activation-pin-pc
welcomeTextOne=Access thousands of real OAU Post Jamb Past Questions
