plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
    id 'org.javamodularity.moduleplugin' version '1.8.12'
    id 'org.beryx.jlink' version '2.25.0'
//    id 'signing'
//    id 'org.sqlite'
}

def build = System.getenv("build")
def buildP = System.getProperty("build")

System.out.println("Build: " + build)
System.out.println("BuildP: " + buildP)

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('src/' + build + '/resources/exam.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

def applicationIdSuffix = keystoreProperties['applicationIdSuffix']
def appName = keystoreProperties['appName']
def appVersion = keystoreProperties['versionName']
def srcPath = keystoreProperties['srcPath']
def appId = keystoreProperties['appId']

group 'com.scholarly' + applicationIdSuffix
version = appVersion

repositories {
    mavenCentral()
    google()

    maven {
        url "https://sandec.jfrog.io/artifactory/repo"
    }
}

ext {
    junitVersion = '5.9.2'
}

sourceCompatibility = '16'
targetCompatibility = '16'

project.ext.buildDate = new Date()
project.version = appVersion

sourceSets {
    /*release {
        java {
            srcDirs 'src/main/java', 'src/release/java'
        }
    }

    debug {
        java {
            srcDirs 'src/main/java', 'src/debug/java'
        }
    }*/

    if (srcPath != null && !srcPath.isEmpty()) {
        main {
            resources {
                srcDirs srcPath
            }
        }
    }
}

tasks.register('stuffZip', Zip) {
    archiveBaseName = 'stuff'
    from 'src/main'
}

//signing {
//    def signingKey = findProperty("signingKeyId")
//    def signingPassword = findProperty("signingPassword")
//    useInMemoryPgpKeys(signingKey as String, signingPassword as String)
////    sign configurations.archives
////    sign configurations.runtimeElements
//    sign stuffZip
//}

application {
    mainModule = 'com.scholarly'
    mainClass = 'com.scholarly.MainApplication'
}

java {
    modularity.inferModulePath.set(false)
}

javafx {
    version = '18.0.2'
    modules = ['javafx.base', 'javafx.graphics', 'javafx.controls', 'javafx.fxml', 'javafx.web', 'javafx.swing']
}

//mainClassName = "$moduleName/com.scholarly.utme.MainApplication"
//mainClassName = "com.scholarly.utme.MainApplication"

run {
    jvmArgs = ['-Djdk.gtk.version=2']
}

jar {
    duplicatesStrategy(DuplicatesStrategy.EXCLUDE)
}

jlink {
    options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
    launcher {
        name = appName
        jvmArgs = ['-Djdk.gtk.version=2']
    }

    jpackage {
        jvmArgs = ['-splash:$APPDIR/splash.png']

        appVersion = version

        def currentOs = org.gradle.internal.os.OperatingSystem.current()
        def imgType = currentOs.windows ? 'ico' : currentOs.macOsX ? 'icns' : 'png'
        def imgName = srcPath + "/drawable/app_icon.$imgType"
        imageOptions += ['--icon', imgName]
        icon = imgName

        outputDir = "jpackage/" + build

        installerOptions += [
                '--description', appName + " App",
                '--resource-dir', "src/main/resources", /*srcPath,*/
                '--vendor', 'Scholarly Educational Software Ltd',
                '--copyright', 'Copyright 2020-2024 Scholarly Educational Software, Ltd. All Rights reserved',
                '--file-associations', 'src/main/resources/associations.properties',
                '--license-file', 'src/main/resources/license.txt',
                '--app-version', version
        ]

        if(currentOs.windows) {
            installerOptions += ['--win-per-user-install', '--win-dir-chooser', '--win-menu', '--win-shortcut']
        } else if (currentOs.linux) {
            installerOptions += ['--linux-package-name', 'scholarly','--linux-shortcut']
        } else if (currentOs.macOsX) {
            installerOptions += ['--mac-package-name', 'scholarly', '--mac-package-identifier', 'com.scholarly.wassce']
        }
    }

    /*mergedModule {
        additive = true
        excludeRequires 'javafx.base', 'javafx.graphics', 'javafx.controls', 'javafx.fxml', 'javafx.web', 'javafx.swing'
    }*/

    mergedModule {

    }
}

tasks.jpackageImage.doLast {
    copy {
        from "src/main/resources"
        include "splash.png"
        into "build/jpackage/$project.name/app"
    }
}

tasks.withType(JavaCompile) {
    configure(options) {
        options.compilerArgs.add("-XDignore.symbol.file=true")
        options.fork = true
        options.forkOptions.executable = 'javac'
        options.encoding = 'utf-8'
    }
}

/*packagingOptions {
    exclude 'META-INF/LICENSE-LGPL-2.1.txt'
    exclude 'META-INF/LICENSE-LGPL-3.txt'
    exclude 'META-INF/LICENSE-W3C-TEST'
    exclude 'META-INF/DEPENDENCIES'
}*/

dependencies {
    implementation('org.controlsfx:controlsfx:11.1.2') {
        exclude group: 'org.openjfx', module: '*'
    }
    implementation('com.dlsc.formsfx:formsfx-core:11.6.0') {
        exclude group: 'org.openjfx', module: '*'
    }
    implementation('net.synedra:validatorfx:0.4.0') {
        exclude(group: 'org.openjfx', module: '*')
    }
    implementation('org.kordamp.ikonli:ikonli-javafx:12.3.1') {
        exclude group: 'org.openjfx', module: '*'
    }
    implementation('org.kordamp.bootstrapfx:bootstrapfx-core:0.4.0') {
        exclude group: 'org.openjfx', module: '*'
    }
    implementation ('com.jidesoft:jidefx-fields:0.9.1') {
        exclude group: 'org.openjfx', module: '*'
    }

    implementation 'org.openjfx:javafx-controls:19.0.2.1'

    implementation 'org.openjfx:javafx-swing:19.0.2.1'

    // SQL connector
    implementation 'io.github.willena:sqlite-jdbc:3.41.2.1'

    // RxJava
    implementation 'io.reactivex.rxjava3:rxjava:3.1.6'

    //RxJavaFx
    implementation 'org.pdfsam.rxjava3:rxjavafx:3.0.2'

    // mvvmfx
    implementation 'de.saxsys:mvvmfx:1.8.0'

    // Text-to-Speech
    implementation 'net.sf.sociaal:freetts:1.2.2'

    // Gson
    implementation 'com.google.code.gson:gson:2.10.1'

    // Common Collections by Apache
    implementation 'org.apache.commons:commons-collections4:4.4'

    // Apache Commons Lang
    implementation 'org.apache.commons:commons-lang3:3.12.0'

    // OKHttp
    implementation 'com.squareup.okhttp3:okhttp:3.12.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:3.12.0'

    // Unirest
    implementation 'com.mashape.unirest:unirest-java:1.3.1'

    // Jackson
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.14.2'

    // Markdown
    implementation 'org.commonmark:commonmark:0.21.0'
    implementation 'com.vladsch.flexmark:flexmark-all:0.64.8'

    // HTML to Text
    implementation 'org.jsoup:jsoup:1.15.4'

    implementation 'org.unbroken-dome.base62:base62:1.1.0'

//    implementation 'org.bytedeco:javacpp:1.7.6' // Use the latest version
//    implementation 'org.bytedeco.javacpp-presets:webp:1.1.6'

    implementation 'com.twelvemonkeys.imageio:imageio-webp:3.9.4'

    // Katex
//    implementation 'io.github.katexjava:katex-java:0.5.0'
    implementation 'org.codehaus.mojo:latex-maven-plugin:1.1'
//    implementation 'com.github.mikaelstaldal:jlatexmath:1.0.10'
//    implementation 'org.scilab.forge:texworks-core:1.0'
    implementation 'org.scilab.forge:jlatexmath:1.0.7'
//    implementation 'com.googlecode.jlatexmath:jlatexmath:1.0.7'
    implementation 'com.nfbsoftware:latex-converter:1.0.1'
//    implementation 'io.github.egormkn:latexview:0.6.1'

    implementation "com.sandec:mdfx:0.2.12"

    // implementation 'org.xerial:sqlite-jdbc:3.36.0.1'

    // Webcam Library
    implementation 'com.github.sarxos:webcam-capture:0.3.12'


    testImplementation("org.junit.jupiter:junit-jupiter-api:${junitVersion}")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:${junitVersion}")
//    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"

}

test {
    useJUnitPlatform()
}