applicationIdSuffix=.putme.futo
versionCodeWin=1
versionNameWin=1.0.0
versionCodeMac=1
versionNameMac=1.0.0
versionCodeLinux=1
versionNameLinux=1.0.0
appSlug=putme-futo
appId=futo_putme
country=Nigeria
hasMultipleCountries=false
hasTheory=false
includeLiteraryTexts=false
hasNotes=true
appName=Scholarly FUTO Post Jamb CBT
school=futo
website=https://futo.edu.ng
dbName=putme_futo.db
dbVersion=1
srcPath=src/putmeFuto/resources
stagingBaseURL=https://staging.putme.scholarly.africa/api/v1/
prodBaseURL=https://putme.scholarly.africa/api/v1/
stagingClientID=924499222398-ne5djajgfceotaqcaj8pi1jabqbd5idn.apps.googleusercontent.com
prodClientID=616523094012-nend4jo42jod90sdha8sfsibmoa7b9t9.apps.googleusercontent.com
paystackURL=https://paystack.com/pay/postutme-activation-pin-pc
welcomeTextOne=Access thousands of real FUTO Post Jamb Past Questions