applicationIdSuffix=.putme.ui
versionCode=1
versionName=1.0.0
appSlug=putme-ui
appId=absu_ui
country=Nigeria
hasMultipleCountries=false
hasTheory=false
includeLiteraryTexts=true
hasNotes=true
appName=Scholarly UI Post Jamb CBT
school=ui
website=https://www.ui.edu.ng
dbName=putme_ui.db
dbVersion=1
srcPath=src/putmeUi/resources
stagingBaseURL=https://staging.putme.scholarly.africa/api/v1/
prodBaseURL=https://putme.scholarly.africa/api/v1/
stagingClientID=924499222398-ne5djajgfceotaqcaj8pi1jabqbd5idn.apps.googleusercontent.com
prodClientID=616523094012-nend4jo42jod90sdha8sfsibmoa7b9t9.apps.googleusercontent.com
paystackURL=https://paystack.com/pay/postutme-activation-pin-pc
welcomeTextOne=Access thousands of real UI Post Jamb Past Questions

