package com.scholarly.utme.ui.utils;

public enum Screens {

    HOME_SCREEN("HOME_SCREEN"),
    ACCOUNT_SCREEN("ACCOUNT_SCREEN"),
    ACTIVATE_SCREEN("ACTIVATE_SCREEN"),
    APPS_SCREEN("APPS_SCREEN"),
    SETTINGS_SCREEN("SETTINGS_SCREEN"),
    PRACTICE_SCREEN("PRACTICE_SCREEN"),
    PAST_QUESTION_SCREEN("PAST_QUESTION_SCREEN"),
    CBT_GAME_SCREEN("CBT_GAME_SCREEN"),
    NOVELS_SCREEN("NOVELS_SCREEN"),
    NOVELS_GRID_SCREEN("NOVELS_GRID_SCREEN"),
    NOVELS_CHAPTER_LIST_SCREEN("NOVELS_CHAPTER_LIST_SCREEN"),
    NOVELS_CONTENT_SCREEN("NOVELS_CONTENT_SCREEN"),
    NOTES_SCREEN("NOTES_SCREEN"),
    SYLLABUS_SCREEN("SYLLABUS_SCREEN"),
    VIDEOS_SCREEN("VIDEOS_SCREEN"),
    AUDIOS_SCREEN("AUDIOS_SCREEN"),
    LEARNING_CENTER_SCREEN("LEARNING_CENTER_SCREEN");

    private String name;

    Screens(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}
