applicationIdSuffix=.putme.unilorin
versionCode=1
versionName=1.0.0
appSlug=putme-unilorin
appId=unilorin_putme
country=Nigeria
hasMultipleCountries=false
hasTheory=false
includeLiteraryTexts=false
hasNotes=true
appName=Scholarly UNILORIN Post Jamb CBT
school=unilorin
dbName=putme_unilorin.db
dbVersion=1
srcPath=src/putmeUnilorin/resources
stagingBaseURL=https://staging.putme.scholarly.africa/api/v1/
prodBaseURL=https://putme.scholarly.africa/api/v1/
stagingClientID=924499222398-ne5djajgfceotaqcaj8pi1jabqbd5idn.apps.googleusercontent.com
prodClientID=616523094012-nend4jo42jod90sdha8sfsibmoa7b9t9.apps.googleusercontent.com
paystackURL=https://paystack.com/pay/postutme-activation-pin-pc