applicationIdSuffix=.putme.futminna
versionCodeWin=1
versionNameWin=1.0.0
versionCodeMac=1
versionNameMac=1.0.0
versionCodeLinux=1
versionNameLinux=1.0.0
appSlug=putme-futminna
appId=futminna_putme
country=Nigeria
hasMultipleCountries=false
hasTheory=false
includeLiteraryTexts=false
hasNotes=true
appName=Scholarly FUTMINNA Post Jamb CBT
school=futminna
website=https://FUTMINNA.edu.ng
dbName=putme_futminna.db
dbVersion=1
srcPath=src/putmeFutminna/resources
stagingBaseURL=https://staging.putme.scholarly.africa/api/v1/
prodBaseURL=https://putme.scholarly.africa/api/v1/
stagingClientID=924499222398-ne5djajgfceotaqcaj8pi1jabqbd5idn.apps.googleusercontent.com
prodClientID=616523094012-nend4jo42jod90sdha8sfsibmoa7b9t9.apps.googleusercontent.com
paystackURL=https://paystack.com/pay/postutme-activation-pin-pc
welcomeTextOne=Access thousands of real FUTMINNA Post Jamb Past Questions