module com.scholarly.utme {
    requires javafx.controls;
    requires javafx.fxml;
    requires javafx.web;
    requires javafx.media;

    requires org.controlsfx.controls;
    requires com.dlsc.formsfx;
    requires org.kordamp.ikonli.javafx;
    requires org.kordamp.bootstrapfx.core;

    requires java.sql;
    requires io.reactivex.rxjava3;
    requires org.pdfsam.rxjavafx;
    requires sqlite.jdbc;
    requires de.saxsys.mvvmfx;
    requires freetts;
    requires com.google.gson;
    requires java.prefs;
    requires jdk.jsobject;
    requires org.apache.commons.collections4;

    exports com.scholarly.utme;
    exports com.scholarly.utme.controller;
    exports com.scholarly.utme.ui.listcells;
    exports com.scholarly.utme.viewmodels;
    exports com.scholarly.utme.data.dao;
    exports com.scholarly.utme.data.util;
    exports com.scholarly.utme.data.model;

    opens com.scholarly.utme.ui.listcells to javafx.fxml;
    opens com.scholarly.utme.data.model.newDb.contentType to com.google.gson;
    opens com.scholarly.utme.data.model.newDb.contentType.text to com.google.gson;
    opens com.scholarly.utme.data.model.newDb.contentType.image to com.google.gson;
    opens com.scholarly.utme.data.model.newDb.contentType.table to com.google.gson;
    opens com.scholarly.utme.data.model.newDb.contentType.tablehh to com.google.gson;
    opens com.scholarly.utme.data.model.newDb.contentType.audio to com.google.gson;
    opens com.scholarly.utme.data.model.newDb.contentType.video to com.google.gson;
    opens com.scholarly.utme.data.model.newDb.contentType.webview to com.google.gson;
    opens com.scholarly.utme.data.model.newDb.contentType.html to com.google.gson;
    opens com.scholarly.utme.data.model.newDb.contentType.cbt to com.google.gson;
    opens com.scholarly.utme.data.model.newDb.contentType.orderedList to com.google.gson;
    opens com.scholarly.utme.data.model.newDb.contentType.unorderedList to com.google.gson;
    opens com.scholarly.utme to de.saxsys.mvvmfx, javafx.fxml;
    opens com.scholarly.utme.viewmodels to de.saxsys.mvvmfx, javafx.fxml;
    opens com.scholarly.utme.controller to de.saxsys.mvvmfx, javafx.fxml;
    opens com.scholarly.utme.controller.landing_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens com.scholarly.utme.viewmodels.landing_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens com.scholarly.utme.controller.trivia_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens com.scholarly.utme.viewmodels.trivia_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens com.scholarly.utme.controller.novel_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens com.scholarly.utme.viewmodels.novel_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens com.scholarly.utme.controller.audio_video_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens com.scholarly.utme.viewmodels.audio_video_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens com.scholarly.utme.controller.settings_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens com.scholarly.utme.viewmodels.settings_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens com.scholarly.utme.controller.account_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens com.scholarly.utme.viewmodels.account_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens layouts to de.saxsys.mvvmfx, javafx.fxml;
    opens layouts.landing_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens layouts.trivia_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens layouts.novel_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens layouts.audio_video_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens layouts.settings_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens layouts.account_screens to de.saxsys.mvvmfx, javafx.fxml;

    exports com.scholarly.utme.data.model.newDb;
    exports com.scholarly.utme.data.model.novels;
    exports com.scholarly.utme.controller.landing_screens;
    exports com.scholarly.utme.viewmodels.landing_screens;
    exports com.scholarly.utme.controller.trivia_screens;
    exports com.scholarly.utme.viewmodels.trivia_screens;
    exports com.scholarly.utme.controller.novel_screens;
    exports com.scholarly.utme.viewmodels.novel_screens;
    exports com.scholarly.utme.data.model.listItems;
    exports com.scholarly.utme.controller.audio_video_screens;
    exports com.scholarly.utme.viewmodels.audio_video_screens;
    exports com.scholarly.utme.controller.settings_screens;
    exports com.scholarly.utme.viewmodels.settings_screens;
    exports com.scholarly.utme.controller.account_screens;
    exports com.scholarly.utme.viewmodels.account_screens;
}