module com.scholarly.utme {
    requires javafx.controls;
    requires javafx.fxml;
    requires javafx.web;
    requires javafx.media;
    requires javafx.swing;

    requires org.controlsfx.controls;
    requires com.dlsc.formsfx;
    requires org.kordamp.ikonli.javafx;
    requires org.kordamp.bootstrapfx.core;
    requires jidefx.fields;
    requires jidefx.converters;
    requires jidefx.common;
    requires jidefx.decoration;

    requires java.sql;
    requires io.reactivex.rxjava3;
    requires org.pdfsam.rxjavafx;
//    requires sqlite.jdbc;
    requires org.xerial.sqlitejdbc;
    requires de.saxsys.mvvmfx;
    requires freetts;
    requires com.google.gson;
    requires java.prefs;
    requires jdk.jsobject;
    requires org.apache.commons.collections4;
    requires org.apache.commons.lang3;
    requires okhttp3;
    requires okhttp3.logging;
    requires jdk.httpserver;
    requires com.fasterxml.jackson.databind;
    requires org.commonmark;
    requires org.jsoup;
    requires latex.maven.plugin;
    requires latex.converter;
    requires com.sandec.mdfx;
    requires flexmark;
    requires flexmark.util.ast;
    requires flexmark.util.data;
    requires flexmark.all;
    requires flexmark.ext.abbreviation;
//    requires org.scilab.forge;
    requires com.twelvemonkeys.imageio.core;
    requires com.twelvemonkeys.common.image;
    requires com.twelvemonkeys.common.io;
    requires com.twelvemonkeys.common.lang;
    requires com.twelvemonkeys.imageio.metadata;
    requires com.twelvemonkeys.imageio.webp;

    requires webcam.capture;
    requires unirest.java;
    requires json;
    requires java.desktop;
    requires base62;

    exports com.scholarly.utme;
    exports com.scholarly.utme.controller;
    exports com.scholarly.utme.ui.listcells;
    exports com.scholarly.utme.viewmodels;
    exports com.scholarly.utme.data.dao;
    exports com.scholarly.utme.data.util;
    exports com.scholarly.utme.data.model;
    exports com.scholarly.utme.ui.utils;
    exports com.scholarly.utme.network;

//    opens jdk.internal.org.objectweb.asm to ALL-UNNAMED;

    opens com.scholarly.utme.ui.listcells to javafx.fxml;
    opens com.scholarly.utme.network.model to com.google.gson;
    opens com.scholarly.utme.network.model.response to com.google.gson;
    opens com.scholarly.utme.network.model.request to com.google.gson;
    opens com.scholarly.utme.data.model.newDb.contentViewType to com.google.gson;
    opens com.scholarly.utme.data.model.newDb.contentType to com.google.gson;
    opens com.scholarly.utme.data.model.newDb.contentType.text to com.google.gson;
    opens com.scholarly.utme.data.model.newDb.contentType.image to com.google.gson;
    opens com.scholarly.utme.data.model.newDb.contentType.table to com.google.gson;
    opens com.scholarly.utme.data.model.newDb.contentType.tablehh to com.google.gson;
    opens com.scholarly.utme.data.model.newDb.contentType.audio to com.google.gson;
    opens com.scholarly.utme.data.model.newDb.contentType.video to com.google.gson;
    opens com.scholarly.utme.data.model.newDb.contentType.webview to com.google.gson;
    opens com.scholarly.utme.data.model.newDb.contentType.html to com.google.gson;
    opens com.scholarly.utme.data.model.newDb.contentType.cbt to com.google.gson;
    opens com.scholarly.utme.data.model.newDb.contentType.orderedList to com.google.gson;
    opens com.scholarly.utme.data.model.newDb.contentType.unorderedList to com.google.gson;
    opens com.scholarly.utme to de.saxsys.mvvmfx, javafx.fxml;
    opens com.scholarly.utme.viewmodels to de.saxsys.mvvmfx, javafx.fxml;
    opens com.scholarly.utme.controller to de.saxsys.mvvmfx, javafx.fxml;
    opens com.scholarly.utme.controller.landing_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens com.scholarly.utme.viewmodels.landing_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens com.scholarly.utme.controller.trivia_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens com.scholarly.utme.viewmodels.trivia_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens com.scholarly.utme.controller.novel_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens com.scholarly.utme.viewmodels.novel_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens com.scholarly.utme.controller.audio_video_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens com.scholarly.utme.viewmodels.audio_video_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens com.scholarly.utme.controller.settings_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens com.scholarly.utme.viewmodels.settings_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens com.scholarly.utme.controller.account_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens com.scholarly.utme.viewmodels.account_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens com.scholarly.utme.controller.note_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens com.scholarly.utme.controller.practice_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens com.scholarly.utme.controller.syllabus_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens com.scholarly.utme.viewmodels.practice_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens com.scholarly.utme.viewmodels.note_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens com.scholarly.utme.viewmodels.syllabus_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens layouts to de.saxsys.mvvmfx, javafx.fxml;
    opens layouts.landing_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens layouts.trivia_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens layouts.novel_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens layouts.audio_video_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens layouts.settings_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens layouts.account_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens layouts.note_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens layouts.practice_screens to de.saxsys.mvvmfx, javafx.fxml;
    opens layouts.syllabus_screens to de.saxsys.mvvmfx, javafx.fxml;

    exports com.scholarly.utme.data.model.newDb;
    exports com.scholarly.utme.data.model.newDb.contentType;
    exports com.scholarly.utme.data.model.novels;
    exports com.scholarly.utme.network.model;
    exports com.scholarly.utme.network.model.request;
    exports com.scholarly.utme.network.model.response;
    exports com.scholarly.utme.controller.landing_screens;
    exports com.scholarly.utme.viewmodels.landing_screens;
    exports com.scholarly.utme.controller.trivia_screens;
    exports com.scholarly.utme.viewmodels.trivia_screens;
    exports com.scholarly.utme.controller.novel_screens;
    exports com.scholarly.utme.viewmodels.novel_screens;
    exports com.scholarly.utme.data.model.listItems;
    exports com.scholarly.utme.controller.audio_video_screens;
    exports com.scholarly.utme.viewmodels.audio_video_screens;
    exports com.scholarly.utme.controller.settings_screens;
    exports com.scholarly.utme.viewmodels.settings_screens;
    exports com.scholarly.utme.controller.account_screens;
    exports com.scholarly.utme.viewmodels.account_screens;
    exports com.scholarly.utme.controller.note_screens;
    exports com.scholarly.utme.controller.practice_screens;
    exports com.scholarly.utme.controller.syllabus_screens;
    exports com.scholarly.utme.viewmodels.practice_screens;
    exports com.scholarly.utme.viewmodels.note_screens;
    exports com.scholarly.utme.viewmodels.syllabus_screens;
}