applicationIdSuffix=.utme
versionCodeWin=6
versionNameWin=1.0.5
versionCodeMac=1
versionNameMac=1.0.0
versionCodeLinux=1
versionNameLinux=1.0.0
appSlug=utme
appId=jamb_utme
country=Nigeria
hasMultipleCountries=false
hasTheory=false
includeLiteraryTexts=true
hasNotes=true
appName=Scholarly JAMB CBT
school=
website=https://www.jamb.gov.ng
dbName=jamb_utme.db
dbVersion=2
srcPath=src/jamb/resources
stagingBaseURL=https://staging.utme.scholarly.africa/api/v1/
prodBaseURL=https://utme.scholarly.africa/api/v1/
stagingClientID=671999041043-p3grlgbnvrn3ph5fvkf4b52h5vq1oii7.apps.googleusercontent.com
prodClientID=165902144265-ais4ot9qt2rjfj113efqv8h50bp0m1l9.apps.googleusercontent.com
paystackURL=https://paystack.com/pay/utme-activation-pin-pc
welcomeTextOne=Access thousands of real JAMB Past Questions