applicationIdSuffix=.putme.futa
versionCode=1
versionName=1.0.0
appSlug=putme-futa
appId=futa_putme
country=Nigeria
hasMultipleCountries=false
hasTheory=false
includeLiteraryTexts=false
hasNotes=true
appName=Scholarly FUTA Post Jamb CBT
school=futa
dbName=putme_futa.db
dbVersion=1
srcPath=src/putmeFuta/resources
stagingBaseURL=https://staging.putme.scholarly.africa/api/v1/
prodBaseURL=https://putme.scholarly.africa/api/v1/
stagingClientID=924499222398-ne5djajgfceotaqcaj8pi1jabqbd5idn.apps.googleusercontent.com
prodClientID=616523094012-nend4jo42jod90sdha8sfsibmoa7b9t9.apps.googleusercontent.com
paystackURL=https://paystack.com/pay/postutme-activation-pin-pc
welcomeTextOne=Access thousands of real FUTA Post Jamb Past Questions
