applicationIdSuffix=.putme.absu
versionCode=1
versionName=1.0.0
appSlug=putme-absu
appId=absu_putme
country=Nigeria
hasMultipleCountries=false
hasTheory=false
includeLiteraryTexts=false
hasNotes=true
appName=Scholarly ABSU Post Jamb CBT
school=absu
website=https://abiastateuniversity.edu.ng/
dbName=putme_absu.db
dbVersion=1
srcPath=src/putmeAbsu/resources
stagingBaseURL=https://staging.putme.scholarly.africa/api/v1/
prodBaseURL=https://putme.scholarly.africa/api/v1/
stagingClientID=924499222398-ne5djajgfceotaqcaj8pi1jabqbd5idn.apps.googleusercontent.com
prodClientID=616523094012-nend4jo42jod90sdha8sfsibmoa7b9t9.apps.googleusercontent.com
paystackURL=https://paystack.com/pay/postutme-activation-pin-pc
welcomeTextOne=Access thousands of real ABSU Post Jamb Past Questions