applicationIdSuffix=.bece.jss
versionCode=1
versionName=1.0.0
appSlug=bece-jss
appId=bece-jss
country=Nigeria
hasMultipleCountries=false
hasTheory=true
includeLiteraryTexts=false
hasNotes=false
appName=Scholarly BECE NECO CBT
school=
dbName=bece_jss.db
dbVersion=1
srcPath=src/beceJss/resources
stagingBaseURL=https://staging.bece-jss.scholarly.africa
prodBaseURL=https://bece-jss.scholarly.africa
stagingClientID=976105403915-im2asvh95ds2st0bldklua4ft806no4r.apps.googleusercontent.com
prodClientID=976105403915-im2asvh95ds2st0bldklua4ft806no4r.apps.googleusercontent.com
paystackURL=https://paystack.com/pay/bece-neco-activation-pin-pc
welcomeTextOne=Access thousands of real BECE NECO Past Questions



